version: "3"

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    command: hbbs -r 0.0.0.0:21117
    volumes:
      - ${DATA:?}/hbbs:/root
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    ports:
      - 21117:21117
      - 21119:21119
    command: hbbr
    volumes:
      - ${DATA:?}/hbbr:/root
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK:-rustdesk}